Update ci-cd-pipeline.yml

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -57,10 +57,17 @@ jobs:
         path: ./publish
 
     - name: Install AWS CLI
-      run: |
-        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-        unzip awscliv2.zip
-        sudo ./aws/install
+       run:|
+        if ! command -v aws &> /dev/null; then
+          echo "AWS CLI not found. Installing..."
+          sudo apt update
+          sudo apt install -y python3-pip
+          pip3 install awscli --upgrade --user
+          export PATH=$PATH:$HOME/.local/bin
+        else
+          echo "AWS CLI already installed. Updating..."
+          sudo /usr/local/aws-cli/v2/current/bin/aws/install --update
+        fi
         aws --version
 
     - name: Install Elastic Beanstalk CLI
